# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.11
_src_path: gh:algorandfoundation/algokit-python-template
author_email: phanhoangvinhhien@gmail.com
author_name: hien-py
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: hello_marketplace

